# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: Build manual

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: |
          mkdir output

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/manual.html man/manual.md

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/manual.pdf man/manual.md

      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/manual-premium.pdf man/manual-premium.md

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: output

  manpage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install missing software on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y xsltproc docbook-xsl

      - name: build manpage
        run: |
          make man

      - uses: actions/upload-artifact@v4
        with:
          name: cppcheck.1
          path: cppcheck.1
