# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: CI-mingw

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
      - '2.*'
    tags:
      - '2.*'
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: msys2 {0}

jobs:
  # TODO: add CMake build
  build_mingw:
    strategy:
      matrix:
        # only use the latest windows-* as the installed toolchain is identical
        os: [windows-2025]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    timeout-minutes: 19 # max + 3*std of the last 7K runs

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up MSYS2
        uses: msys2/setup-msys2@fb197b72ce45fb24f17bf3f807a388985654d1f2 # v2.29.0
        with:
          release: false # use pre-installed
          # TODO: install mingw-w64-x86_64-make and use mingw32.make instead - currently fails with "Windows Subsystem for Linux has no installed distributions."
          install: >-
            mingw-w64-x86_64-lld
            mingw-w64-x86_64-ccache
            make
            mingw-w64-x86_64-gcc

      - name: ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        with:
          key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.os }}

      - name: Build cppcheck
        run: |
          export PATH="/mingw64/lib/ccache/bin:$PATH"
          # set RDYNAMIC to work around broken MinGW detection
          # use lld for faster linking
          make VERBOSE=1 RDYNAMIC=-lshlwapi LDOPTS=-fuse-ld=lld -j$(nproc) CXXOPTS="-Werror" cppcheck

      - name: Build test
        run: |
          export PATH="/mingw64/lib/ccache/bin:$PATH"
          # set RDYNAMIC to work around broken MinGW detection
          # use lld for faster linking
          make VERBOSE=1 RDYNAMIC=-lshlwapi LDOPTS=-fuse-ld=lld -j$(nproc) CXXOPTS="-Werror" testrunner

      - name: Run test
        run: |
          export PATH="/mingw64/lib/ccache/bin:$PATH"
          # set RDYNAMIC to work around broken MinGW detection
          # use lld for faster linking
          make VERBOSE=1 RDYNAMIC=-lshlwapi LDOPTS=-fuse-ld=lld -j$(nproc) CXXOPTS="-Werror" test
