# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: Coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.workflow }}-${{ runner.os }}

      - name: Install missing software on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils lcov

      - name: Install missing Python packages on ubuntu
        run: |
          python -m pip install pip --upgrade
          python -m pip install lcov_cobertura

      - name: Compile instrumented
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j$(nproc) all CXXFLAGS="-g -fprofile-arcs -ftest-coverage" HAVE_RULES=yes

      - name: Run instrumented tests
        run: |
          ./testrunner
          test/cfg/runtests.sh

      - name: Generate coverage report
        run: |
          gcov lib/*.cpp -o lib/
          lcov --directory ./ --capture --output-file lcov_tmp.info -b ./
          lcov --extract lcov_tmp.info "$(pwd)/*" --output-file lcov.info
          genhtml lcov.info -o coverage_report --frame --legend --demangle-cpp
          
      - uses: actions/upload-artifact@v3
        with:
         name: Coverage results
         path: coverage_report
         
      - uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # file: ./coverage.xml # optional
          flags: unittests # optional
          name: ${{ github.repository }} # optional
          fail_ci_if_error: true # optional (default = false):  
